"""add three tables

Revision ID: 313cee0dc052
Revises: 
Create Date: 2022-10-07 23:08:05.075471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '313cee0dc052'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('table_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'table', ['table_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'table_id')
    # ### end Alembic commands ###
